ARG CONTAINER_USER="nonrootuser"

FROM alpine:3.14 as base

ARG CONTAINER_USER

RUN  apk update \
    apk add --no-cache bash git curl wget jq bind-tools ;\
    apk add --no-cache --update --virtual .ansible_deps python3-dev ;\
    rm -rf /var/cache/apk/* /tmp/* /sbin/halt /sbin/poweroff /sbin/reboot

RUN if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi ;\
    python3 -m ensurepip ;\
    rm -r /usr/lib/python*/ensurepip ;\
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi ;\
    pip3 install --no-cache --upgrade \
      pip \
      setuptools \
      wheel \
      "ansible>=2.10" \
      "PyYAML>=3.11" \
      yq

RUN adduser -s /bin/bash -u 1000 -D -h /home/${CONTAINER_USER} ${CONTAINER_USER} ${CONTAINER_USER}
USER ${CONTAINER_USER}

WORKDIR /home/${CONTAINER_USER}